lets not remove snapd for now in auto mode. may still have snaps you need

diff --git a/unsnap b/unsnap
--- a/unsnap
+++ b/unsnap
@@ -312,13 +312,13 @@ function run_scripts() {
         echo "ERROR: Failed to remove snaps" | tee -a "$LOGFILE"
         exit 14
     fi
-    echo "INFO: Removing snapd daemon" | tee -a "$LOGFILE"
-    if "$REMOVESNAPDSCRIPT"; then
-        echo "INFO: snapd removed" | tee -a "$LOGFILE"
-    else
-        echo "ERROR: Failed to remove snapd" | tee -a "$LOGFILE"
-        exit 15
-    fi
+    # echo "INFO: Removing snapd daemon" | tee -a "$LOGFILE"
+    # if "$REMOVESNAPDSCRIPT"; then
+    #     echo "INFO: snapd removed" | tee -a "$LOGFILE"
+    # else
+    #     echo "ERROR: Failed to remove snapd" | tee -a "$LOGFILE"
+    #     exit 15
+    # fi
 }
 
 function recommend_reboot() {
